# Generated by Django 5.2.17 on 2026-09-23 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model_type', models.CharField(choices=[('CSV', 'CSV / Tabular Classification'), ('IMAGE', 'Image Classification')], default='CSV', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATING', 'Validating'), ('TRAINING', 'Training'), ('TRAINED', 'Trained'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('artifact_reference', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'status'], name='models_mlmo_owner_i_8a0c98_idx'), models.Index(fields=['model_type', 'status'], name='models_mlmo_model_t_db9de0_idx')],
            },
        ),
    ]
