# Generated by Django 5.2.17 on 2026-09-24 12:43

from django.db import migrations, models


def migrate_roles_to_developer(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="CUSTOMER").update(role="DEVELOPER")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_verification_email_sent_at'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='user_role_is_valid',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('DEVELOPER', 'Developer')], db_index=True, default='DEVELOPER', max_length=20),
        ),
        migrations.RunPython(
            migrate_roles_to_developer,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['SUPER_ADMIN', 'DEVELOPER'])), name='user_role_is_valid'),
        ),
    ]
